name: mobile
version: 0.1.0
summary: The automatic pot watering system
description: The automatic pot watering system

confinement: strict
base: core18
grade: stable

slots:
  mobile:
    interface: dbus
    bus: session
    name: com.hendrychjan.bazalka.mobile
    
apps:
  mobile:
    command: mobile
    extensions: [flutter-master] 
    plugs:
    - network
    slots:
      - dbus-super-cool-app
parts:
  mobile:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
